<script setup lang="ts">
import NavMenu from '@/components/NavMenu.vue';
import Footer from '@/components/Footer.vue';
import { Head, Link } from '@inertiajs/vue3';
defineProps<{ products: any; categories: any[] }>();
</script>
<template><Head title="Katalog Produk"/><div class="min-h-screen bg-white text-gray-900"><NavMenu/>
<section class="bg-gradient-to-br from-slate-900 to-slate-700 px-4 py-24 text-white"><div class="mx-auto max-w-6xl"><p class="mb-3 text-sm uppercase tracking-widest text-blue-300">Katalog Produk</p><h1 class="max-w-3xl text-4xl font-bold md:text-5xl">Produk yang Kami Jual</h1><p class="mt-4 max-w-2xl text-slate-200">Jelajahi katalog produk kami. Tidak ada cart atau checkout, silakan hubungi tim kami untuk konsultasi dan pemesanan.</p></div></section>
<section class="px-4 py-16"><div class="mx-auto max-w-6xl"><div v-if="categories.length" class="mb-8 flex flex-wrap gap-2"><span v-for="category in categories" :key="category.id" class="rounded-full border px-4 py-2 text-sm" :style="{ borderColor: category.color }">{{ category.name }}</span></div><div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3"><Link v-for="product in products.data" :key="product.id" :href="route('products.show', product.slug)" class="group overflow-hidden rounded-2xl border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div class="aspect-video bg-slate-100"><img v-if="product.image_url" :src="product.image_url" :alt="product.name" class="h-full w-full object-cover"/><div v-else class="flex h-full items-center justify-center text-slate-400">No Image</div></div><div class="p-5"><div class="mb-2 flex items-center justify-between gap-2"><span class="text-sm text-blue-600">{{ product.category?.name ?? 'Produk' }}</span><span v-if="product.featured" class="rounded-full bg-yellow-100 px-2 py-1 text-xs text-yellow-700">Featured</span></div><h2 class="text-xl font-semibold group-hover:text-blue-600">{{ product.name }}</h2><p class="mt-2 line-clamp-2 text-sm text-slate-600">{{ product.summary }}</p><p v-if="product.price_label" class="mt-4 font-semibold text-slate-900">{{ product.price_label }}</p></div></Link></div><div v-if="!products.data.length" class="rounded-xl border p-8 text-center text-slate-500">Belum ada produk yang dipublikasikan.</div></div></section>
<Footer/></div></template>
